autotest/urls.py
from django.contrib import admin
from django.urls import path
from apitest import views
from apptest import appviews
from webtest import webviews
from product import proviews
from set import setviews
from bug import bugviews

urlpatterns = [
    path('admin/', admin.site.urls),
  #  path('test/', views.test),
    path('task_apis/', views.task_apis),
    path('task_apitest/', views.task_apitest),
    path('task_webtest/', views.task_webtest),
    path('task_webtest2/', views.task_webtest2),
    path('task_apptest/', views.task_apptest),
    path('task_apptest2/', views.task_apptest2),
    path('login/', views.login),
    path('', views.login),
    path('logout/', views.logout),
    path('home/', views.home),
    path ('welcome/', views.welcome),
    path('product_manage/', proviews.product_manage),
    path('productsearch/', proviews.productsearch),
    path('apitest_manage/', views.apitest_manage),
    path('apistep_manage/', views.apistep_manage,name='apistep_manage'),
    path('left/', views.left),
    path('apisearch/', views.apisearch),
    path('apistepsearch/', views.apistepsearch),
    path('apissearch/', views.apissearch),
    path('apis_manage/', views.apis_manage),
    path('periodic_task/', views.periodic_task), 
    path('tasksearch/', views.tasksearch), 
    path('appcase_manage/', appviews.appcase_manage),
    path('appcasestep_manage/', appviews.appcasestep_manage,name='appcasestep_manage'),
    path('appsearch/', appviews.appsearch),
    path('appstepsearch/', appviews.appstepsearch),
    path('webcase_manage/', webviews.webcase_manage),
    path('webcasestep_manage/', webviews.webcasestep_manage,name='webcasestep_manage'),
    path('websearch/', webviews.websearch),
    path('webstepsearch/', webviews.webstepsearch),
    path('webtest_report/', webviews.webtest_report),
    path('apitest_report/', views.apitest_report),
    path('apptest_report/', appviews.apptest_report),
    path('test_report/', views.test_report),
    path('set_manage/', setviews.set_manage),
    path ('setsearch/', setviews.setsearch),
    path ('usersearch/', setviews.usersearch),
    path('user/', setviews.set_user),
    path('bug_manage/', bugviews.bug_manage),
    path ('bugsearch/', bugviews.bugsearch),

]

apptest/models.py
# -*- coding:utf-8 -*-
#####################################
#作者：邹辉《自动化平台测试开发》书
#日期：2018年1月
#版本：autotestplat V1.0
#####################################
from django.db import models
from product.models import Product
# Create your models here.

class Appcase(models.Model):
    Product = models.ForeignKey('product.Product',on_delete=models.CASCADE,null=True)        # 关联产品id
    appcasename = models.CharField('用例名称',max_length=200)       # 测试用例名称
    apptestresult = models.BooleanField('测试结果')                 # 测试结果
    apptester = models.CharField('测试负责人',max_length=16)        # 执行人
    create_time = models.DateTimeField('创建时间',auto_now=True)    # 创建时间-自动获取当前时间
    class Meta:
        verbose_name = 'app测试用例'
        verbose_name_plural = 'app测试用例'
    def __str__(self):
        return self.appcasename
	
class Appcasestep(models.Model):
    Appcase = models.ForeignKey('Appcase',on_delete=models.CASCADE)    # 关联接口id
    appteststep = models.CharField('测试步聚',max_length=200)        # 测试步聚
    apptestobjname = models.CharField('测试对象名称描述',max_length=200) # 测试对象名称描述
    appfindmethod = models.CharField('定位方式',max_length=200)      # 定位方式
    appevelement = models.CharField('控件元素',max_length=800)       # 控件元素
    appoptmethod = models.CharField('操作方法',max_length=200)       # 操作方法
    apptestdata = models.CharField('测试数据',max_length=200,null=True)       # 测试数据
    appassertdata = models.CharField('验证数据',max_length=200)      # 验证数据
    apptestresult = models.BooleanField('测试结果')                  # 测试结果
    create_time = models.DateTimeField('创建时间',auto_now=True)     # 创建时间-自动获取当前时间
    def __str__(self):
        return self.appteststep

apptest/templates/appcase_manage.html
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>产品自动化测试平台</title>
<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<!--<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
  -->
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />



<script type="text/javascript" src="/admin/jsi18n/"></script>

<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>

<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>

<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>

<script type="text/javascript" src="/static/admin/js/urlify.js"></script>

<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>

<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>


    
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
    


<meta name="robots" content="NONE,NOARCHIVE" />


</head>
<body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<li class="active"><a style='color:white' href="/apis_manage/">单一接口</a></li> 
&nbsp;&nbsp;&nbsp;&nbsp;
<li><a style='color:white' href="/apitest_manage/">流程接口</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/appcase_manage/">app用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/webcase_manage/">web用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<ul class="nav justify-content-center"> 
</ul>
<ul class="nav justify-content-end" style="position:absolute; right:10px; bottom:0px; ">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/logout/">退出</a></li>
</ul>
</div>
</nav>
<!-- 搜索栏--> 
<div class="page-header" style="padding-top:0px">
<form class="navbar-form" method="get" action="/appsearch/">
 
{% csrf_token %}     
<input type="search" name="appcasename" placeholder="名称" required>
  
<button type="submit">搜索</button>
 

<!-- 增加app测试用例-->
<div style="float:right;width:65%">

<select name="Appcase" id="id_Appcase">
<option value="" selected>------app测试用例------</option>
</select>
<a class="related-widget-wrapper-link change-related" id="change_id_Appcase" data-href-template="/admin/apptest/appcase/__fk__/change/?_to_field=id&amp;_popup=1" title="更改选中的测试用例">
<img src="/static/admin/img/icon-changelink.svg" alt="修改"/>
</a>
<a class="related-widget-wrapper-link add-related" id="add_id_Appcase" href="/admin/apptest/appcase/add/?_to_field=id&amp;_popup=1" title="增加另一个 测试用例">
<img src="/static/admin/img/icon-addlink.svg" alt="增加"/>增加
</a>
</form>
</div>

<!-- 流程接口列表-->
<div class="row" style="padding-top:20px;width:100%">
<div class="col-md-12">
<table class="table table-striped">
<thead>

<tr>
<th>ID</th><th>产品</th><th>用例名称</th><th>结果</th><th>负责人</th><th>时间</th><th>查看</th><th>编辑</th><th>删除</th>
</tr>
</thead>
<tbody>
{% for appcase in appcases %}
<tr>
<td>{{ appcase.id }}</td>
<td>{{ appcase.Product.productname }}</td>
<td>{{ appcase.appcasename }}</td>
<td>{{ appcase.apptestresult }}</td>
<td>{{ appcase.apptester }}</td>
<td>{{ appcase.create_time }}</td> 
<td><a href="{% url "appcasestep_manage" %}?appcase.id={{ appcase.id  }} "><img src="/static/admin/img/icon-yes.svg"/></a></td> 
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Appcase" href="../admin/apptest/appcase/{{ appcase.id  }}/change/?_to_field=id&_popup=1"><img src="/static/admin/img/icon-changelink.svg"/></a></td>
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Appcase" href="../admin/apptest/appcase/{{ appcase.id  }}/delete/?_to_field=id&_popup=1"><img src="/static/admin/img/icon-deletelink.svg"/></a></td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>

<!--统计和翻页功能-->
<span style="position:absolute; left:600px; bottom:30px;">   {# 把翻页功能固定显示在右下角#}
<div style="position:absolute; right:950px; bottom:25px; width:100px;">
共:{{ appcasecounts }}条记录 {# 前端读取定义的变量#}
</div>

<div class="container">
    <ul class="pagination" id="pager">
          {# 上一页链接开始#}
        {% if appcases.has_previous %}
            {#  如果有上一页则正常显示上一页链接#}
            <li class="previous"><a href="/appcase_manage/?page={{ appcases.previous_page_number }}">上一页</a></li>    {#  上一页标签 #}
        {% else %}
            <li class="previous disabled"><a href="#">上一页</a></li> {# 如果当前不存在上一页则上一页的链接不可点击#}
        {% endif %}
        {# 上一页链接开始#}
        
        {% for num in appcases.paginator.page_range %}
         
            {% if num == currentPage %}
                <li class="item active"><a href="/appcase_manage/?page={{ num }}">{{ num }}</a></li> {#显示当页数链接#} 
            {% else %}
                <li class="item"><a href="/appcase_manage/?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
        
        {# 下一页链接开始#}
        {% if appcases.has_next %} {#  如果有下一页则正常显示下一页链接#}
            <li class="next"><a href="/appcase_manage/?page={{ appcases.next_page_number }}">下一页</a></li>
        {% else %}
            <li class="next disabled"><a href="#">下一页</a></li>
        {% endif %}
        {# 下一页链接结束#}
    </ul>
</div>



<script type="text/javascript"
  id="django-admin-form-add-constants"
 src="/static/admin/js/change_form.js"
  data-model-name="appcase"
>
</script>






<script type="text/javascript"
  id="django-admin-prepopulated-fields-constants"
  src="/static/admin/js/prepopulate_init.js"
 data-prepopulated-fields="[]">
</script>

</body>
</html>

apptest/templates/appcasestep_manage.html
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>产品自动化测试平台</title>
<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />

<script type="text/javascript" src="/admin/jsi18n/"></script>



<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>

<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>

<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>

<script type="text/javascript" src="/static/admin/js/urlify.js"></script>

<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>

<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>


    
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
    


<meta name="robots" content="NONE,NOARCHIVE" />
<style> body{text-align:center} </style> 
</head>
<body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<li class="active"><a style='color:white' href="/apis_manage/">单一接口</a></li> 
&nbsp;&nbsp;&nbsp;&nbsp;
<li><a style='color:white' href="/apitest_manage/">流程接口</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/appcase_manage/">app用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<li class="active"><a style='color:white' href="/webcase_manage/">web用例</a></li>
&nbsp;&nbsp;&nbsp;&nbsp;
<ul class="nav justify-content-center">  
</ul>
<ul class="nav justify-content-end" style="position:absolute; right:10px; bottom:0px; ">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/logout/">退出</a></li>
</ul>
</div>
</nav>


<!-- 流程测试步聚-->
<div class="row" style="padding-top: 0px;">
<div class="col-md-12">
<table class="table table-striped">
<thead>
<tr> 
<th>产品</th><th>所属用例</th><th>步聚</th><th>定位方式</th><th>控件元素</th><th>操作方法</th><th>测试数据</th><th>验证数据</th><th>测试结果</th><th>时间</th>
</tr>
</thead>
<tbody>
{% for appcasestep in appcasesteps %}
<tr>
{% if appcasestep.Appcase.id == appcase.id  %}
<td>{{ appcasestep.Appcase.Product.productname }}</td>
<td>case_{{ appcasestep.Appcase.id }}_{{ appcasestep.Appcase.appcasename }}</td>
<td>{{ appcasestep.appteststep }}:{{ appcasestep.apptestobjname }}</td>
<td>{{ appcasestep.appfindmethod }}</td>
<td>{{ appcasestep.appevelement }}</td>
<td>{{ appcasestep.appoptmethod }}</td>
<td>{{ appcasestep.apptestdata }}</td>
<td>{{ appcasestep.appassertdata }}</td>
<td>{% if appcasestep.apptestresult == 1 %}
<a style='color:green'>{{ appcasestep.apptestresult }}</a> 
{% else %}
<a style='color:red'>{{ appcasestep.apptestresult }}</a> 
{% endif %}
</td>
<td>{{ appcasestep.create_time }}</td> 
{% else %}
{% endif %}
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
<td>
<a style='color:light blue'  href="../appcase_manage/" >
<img src="/static/admin/img/icon-yes.svg" alt="返回"/>返回
</a>
</td>

<td>
<a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Appcase" href="../admin/apptest/appcase/{{ appcase.id  }}/change/?_to_field=id&_popup=1">
<img src="/static/admin/img/icon-changelink.svg"/>编辑</a>
</td>

</body>
</html>

apptest/templates/apptest_report.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>app自动化测试汇总报告</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    
<style type="text/css" media="screen">
body        { font-family: verdana, arial, helvetica, sans-serif; font-size: 80%; }
table       { font-size: 100%; }
pre         { }

/* -- heading ---------------------------------------------------------------------- */
h1 {
	font-size: 16pt;
	color: gray;
}
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}

.heading .attribute {
    margin-top: 1ex;
    margin-bottom: 0;
}

.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}

/* -- css div popup ------------------------------------------------------------------------ */
a.popup_link {
}

a.popup_link:hover {
    color: red;
}

.popup_window {
    display: none;
    position: relative;
    left: 0px;
    top: 0px;
    /*border: solid #627173 1px; */
    padding: 10px;
    background-color: #E6E6D6;
    font-family: "Lucida Console", "Courier New", Courier, monospace;
    text-align: left;
    font-size: 8pt;
    width: 500px;
}

}
/* -- report ------------------------------------------------------------------------ */
#show_detail_line {
    margin-top: 3ex;
    margin-bottom: 1ex;
}
#result_table {
    width: 80%;
    border-collapse: collapse;
    border: 1px solid #777;
}
#header_row {
    font-weight: bold;
    color: white;
    background-color: #777;
}
#result_table td {
    border: 1px solid #777;
    padding: 2px;
}
#total_row  { font-weight: bold; }
.passClass  { background-color: #6c6; }
.failClass  { background-color: #c60; }
.errorClass { background-color: #c00; }
.passCase   { color: #6c6; }
.failCase   { color: #c60; font-weight: bold; }
.errorCase  { color: #c00; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }


/* -- ending ---------------------------------------------------------------------- */
#ending {
}

</style>

</head>
<body>
<script language="javascript" type="text/javascript"><!--
output_list = Array();

/* level - 0:Summary; 1:Failed; 2:All */
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level < 1) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level > 1) {
                tr.className = '';
            }
            else {
                tr.className = 'hiddenRow';
            }
        }
    }
}


function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        tid0 = 't' + cid.substr(1) + '.' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        if (toHide) {
            document.getElementById('div_'+tid).style.display = 'none'
            document.getElementById(tid).className = 'hiddenRow';
        }
        else {
            document.getElementById(tid).className = '';
        }
    }
}


function showTestDetail(div_id){
    var details_div = document.getElementById(div_id)
    var displayState = details_div.style.display
    // alert(displayState)
    if (displayState != 'block' ) {
        displayState = 'block'
        details_div.style.display = 'block'
    }
    else {
        details_div.style.display = 'none'
    }
}


function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}

/* obsoleted by detail in <div>
function showOutput(id, name) {
    var w = window.open("", //url
                    name,
                    "resizable,scrollbars,status,width=800,height=450");
    d = w.document;
    d.write("<pre>");
    d.write(html_escape(output_list[id]));
    d.write("\n");
    d.write("<a href='javascript:window.close()'>close</a>\n");
    d.write("</pre>\n");
    d.close();
}
*/
--></script>

<div class='heading'>
<h1>app自动化测试汇总报告</h1>
<p class='attribute'><strong>Start Time:</strong> 2018-01-12 00:02:06</p>
<p class='attribute'><strong>Duration:</strong> 0:01:01.446684</p>
<p class='attribute'><strong>Status:</strong> Pass 1</p>

<p class='description'>app自动化测试</p>
</div>



<p id='show_detail_line'>Show
<a href='javascript:showCase(0)'>Summary</a>
<a href='javascript:showCase(1)'>Failed</a>
<a href='javascript:showCase(2)'>All</a>
</p>
<table id='result_table'>
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row'>
    <td>Test Group/Test case</td>
    <td>Count</td>
    <td>Pass</td>
    <td>Fail</td>
    <td>Error</td>
    <td>View</td>
</tr>

<tr class='passClass'>
    <td>Calculator</td>
    <td>1</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td><a href="javascript:showClassDetail('c1',1)">Detail</a></td>
</tr>

<tr id='pt1.1' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_readSQLcase</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_pt1.1')" >
        pass</a>

    <div id='div_pt1.1' class="popup_window">
        <div style='text-align: right; color:red;cursor:pointer'>
        <a onfocus='this.blur();' onclick="document.getElementById('div_pt1.1').style.display = 'none' " >
           [x]</a>
        </div>
        <pre>
        
pt1.1: 

        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='total_row'>
    <td>Total</td>
    <td>1</td>
    <td>1</td>
    <td>0</td>
    <td>0</td>
    <td>&nbsp;</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>

</body>
</html>