autotest/urls.py
from django.contrib import admin
from django.urls import path
from apitest import views
from apptest import appviews
from webtest import webviews
from product import proviews
from set import setviews
from bug import bugviews

urlpatterns = [
    path('admin/', admin.site.urls),
  #  path('test/', views.test),
    path('task_apis/', views.task_apis),
    path('task_apitest/', views.task_apitest),
    path('task_webtest/', views.task_webtest),
    path('task_webtest2/', views.task_webtest2),
    path('task_apptest/', views.task_apptest),
    path('task_apptest2/', views.task_apptest2),
    path('login/', views.login),
    path('', views.login),
    path('logout/', views.logout),
    path('home/', views.home),
    path ('welcome/', views.welcome),
    path('product_manage/', proviews.product_manage),
    path('productsearch/', proviews.productsearch),
    path('apitest_manage/', views.apitest_manage),
    path('apistep_manage/', views.apistep_manage,name='apistep_manage'),
    path('left/', views.left),
    path('apisearch/', views.apisearch),
    path('apistepsearch/', views.apistepsearch),
    path('apissearch/', views.apissearch),
    path('apis_manage/', views.apis_manage),
    path('periodic_task/', views.periodic_task), 
    path('tasksearch/', views.tasksearch), 
    path('appcase_manage/', appviews.appcase_manage),
    path('appcasestep_manage/', appviews.appcasestep_manage,name='appcasestep_manage'),
    path('appsearch/', appviews.appsearch),
    path('appstepsearch/', appviews.appstepsearch),
    path('webcase_manage/', webviews.webcase_manage),
    path('webcasestep_manage/', webviews.webcasestep_manage,name='webcasestep_manage'),
    path('websearch/', webviews.websearch),
    path('webstepsearch/', webviews.webstepsearch),
    path('webtest_report/', webviews.webtest_report),
    path('apitest_report/', views.apitest_report),
    path('apptest_report/', appviews.apptest_report),
    path('test_report/', views.test_report),
    path('set_manage/', setviews.set_manage),
    path ('setsearch/', setviews.setsearch),
    path ('usersearch/', setviews.usersearch),
    path('user/', setviews.set_user),
    path('bug_manage/', bugviews.bug_manage),
    path ('bugsearch/', bugviews.bugsearch),

]

bug/models.py
# -*- coding:utf-8 -*-
#####################################
#作者：邹辉《自动化平台测试开发》书
#日期：2018年1月
#版本：autotestplat V1.0
#####################################
from django.db import models
from product.models import Product

class Bug(models.Model):
    Product = models.ForeignKey('product.Product',on_delete=models.CASCADE,null=True)        # 关联产品id
    bugname = models.CharField('bug名称',max_length=64)  # bug名称
    bugdetail = models.CharField('bug详情',max_length=2000)# bug详情
    BUG_STATUS = (('激活', '激活'),('已解决', '已解决'),('已关闭', '已关闭'))
    bugstatus = models.CharField(verbose_name='解决状态',choices = BUG_STATUS,default='激活',max_length=200,null=True)# 解决状态
    BUG_LEVEL = (('1', '1'),('2', '2'),('3', '3'))
    buglevel = models.CharField(verbose_name='严重程度',choices = BUG_LEVEL,default='3',max_length=200,null=True)# 严重程度
    bugcreater = models.CharField('创建人',max_length=200)# 创建人
    bugassign = models.CharField('分配给',max_length=200)# 分配给
    created_time = models.DateTimeField('创建时间',auto_now=True)# 更新时间值
    class Meta:
        verbose_name = 'bug管理'
        verbose_name_plural = 'bug管理'
    def __str__(self):
        return self.bugname

product/models.py
# -*- coding:utf-8 -*-
#####################################
#作者：邹辉《自动化平台测试开发》书
#日期：2018年1月
#版本：autotestplat V1.0
#####################################
from django.db import models

# Create your models here.

class Product(models.Model):
    productname = models.CharField('产品名称',max_length=64)  # 产品名称
    productdesc = models.CharField('产品描述',max_length=200)    # 产品描述
    producter = models.CharField('产品负责人',max_length=200,null=True)    # 产品负责人
    create_time = models.DateTimeField('创建时间',auto_now=True)  # 创建时间-自动获取当前时间
    class Meta:
        verbose_name = '产品管理'
        verbose_name_plural = '产品管理'
    def __str__(self):
        return self.productname

product/templates/product_manage.html
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>产品自动化测试平台</title>
<link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}" />
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
<meta name="robots" content="NONE,NOARCHIVE" />
</head>
<body role="document">
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<ul class="nav justify-content-left"> &nbsp;
</ul>
<ul class="nav justify-content-center"> &nbsp;
</ul>
<ul class="nav justify-content-end" style="position:absolute; right:10px; bottom:0px; ">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/logout/">退出</a></li>
</ul>
</div>
</nav>
<!-- 搜索栏-->
<div class="page-header" style="padding-top: 0px;">
<form class="navbar-form" method="get" action="/productsearch/">
 
{% csrf_token %}     
<input type="search" name="productname" placeholder="名称" required>
  
<button type="submit">搜索</button>
    
<!-- 增加产品-->
<div style="float:right;width:65%">

<select name="Product" id="id_Product">
<option value="" selected>----产品----</option>
</select>
<a class="related-widget-wrapper-link change-related" id="change_id_Product" data-href-template="/admin/product/product/__fk__/change/?_to_field=id&amp;_popup=1" title="更改选中的产品">
<img src="/static/admin/img/icon-changelink.svg" alt="修改"/>
</a>
<a class="related-widget-wrapper-link add-related" id="add_id_Product" href="/admin/product/product/add/?_to_field=id&amp;_popup=1" title="增加另一个 产品">
<img src="/static/admin/img/icon-addlink.svg" alt="增加"/>增加
</a>
</form>
</div>

<!-- 产品列表-->
<div class="row" style="padding-top: 20px;">
<div class="col-md-12">
<table class="table table-striped">
<thead>

<tr>
<th>ID</th><th>产品名称</th><th>产品描述</th><th>产品负责人</th><th>创建时间</th><th>编辑</th><th>删除</th>
</tr>
</thead>
<tbody>
{% for product in products %}
<tr>
<td>{{ product.id }}</td>
<td>{{ product.productname }}</td>
<td>{{ product.productdesc }}</td>
<td>{{ product.producter }}</td>
<td>{{ product.create_time }}</td> 
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Product" href="../admin/product/product/{{ product.id  }}/change/?_to_field=id&_popup=1"><img src="/static/admin/img/icon-changelink.svg"/></a></td>
<td><a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Product" href="../admin/product/product/{{ product.id  }}/delete/?_to_field=id&_popup=1"><img src="/static/admin/img/icon-deletelink.svg"/></a></td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>

<!--统计和翻页功能-->
<span style="position:absolute; left:600px; bottom:30px;">   {# 把翻页功能固定显示在右下角#}
<div style="position:absolute; right:950px; bottom:25px; width:100px;">
共:{{ productcounts }}条记录 {# 前端读取定义的变量#}
</div>
<div class="container" >

    <ul class="pagination" id="pager">
          {# 上一页链接开始#}
        {% if products.has_previous %}
            {#  如果有上一页则正常显示上一页链接#}
            <li class="previous"><a href="/product_manage/?page={{ products.previous_page_number }}">上一页</a></li>    {#  上一页标签 #}
        {% else %}
            <li class="previous disabled"><a href="#">上一页</a></li> {# 如果当前不存在上一页则上一页的链接不可点击#}
        {% endif %}
        {# 上一页链接开始#}
        
        {% for num in products.paginator.page_range %}
         
            {% if num == currentPage %}
                <li class="item active"><a href="/product_manage/?page={{ num }}">{{ num }}</a></li> {#显示当页数链接#} 
            {% else %}
                <li class="item"><a href="/product_manage/?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
        
        {# 下一页链接开始#}
        {% if products.has_next %} {#  如果有下一页则正常显示下一页链接#}
            <li class="next"><a href="/product_manage/?page={{ products.next_page_number }}">下一页</a></li>
        {% else %}
            <li class="next disabled"><a href="#">下一页</a></li>
        {% endif %}
        {# 下一页链接结束#}
    </ul>

</div>
</body>
</html>